In [1]:
# 2019-03-12 Etienne Bayard for Capstone project McGill YCBS256
#in Colabs after uploading files 2005_2017datamtleng.csv & 2018datamtleng.csv

# Using pandas library for data management
import pandas as pd

# using numpy for mathematical functions
import numpy as np

# Read the files into DataFrames: 
data_train = pd.read_csv('2005_2017datamtleng.csv')
data_test = pd.read_csv('2018datamtleng.csv')

# View the heads of the DataFrames
print(data_train.head())
print(data_test.head())

         Date  Nombre incidents   Quote  Jour de la semaine  Weekday  \
0  2005-01-01                 4  Medium                   7  Weekend   
1  2005-01-02                 1     Low                   1  Weekend   
2  2005-01-03                 4  Medium                   2     Week   
3  2005-01-04                 8    High                   3     Week   
4  2005-01-05                 9    High                   4     Week   

   Max Temp (C)  Min Temp (C)  Mean Temp (C)  Heat Deg Days (C)  \
0           6.4         -12.0           -2.8               20.8   
1          -5.4         -15.9          -10.7               28.7   
2           1.2          -7.1           -3.0               21.0   
3          -2.1          -7.1           -4.6               22.6   
4          -4.0         -14.3           -9.2               27.2   

   Cool Deg Days (C)  Total Precip (mm)  Snow on Grnd (cm)  
0                0.0                0.2                  2  
1                0.0               11.4   

In [2]:
#One hot encode categorical data
#http://www.insightsbot.com/blog/zuyVu/python-one-hot-encoding-with-pandas-made-simple
df_train_dummies = pd.get_dummies(data_train[['Quote','Weekday']], prefix = 'category')
print(data_train[['Quote','Weekday']].head())
print(df_train_dummies.head())

df_test_dummies = pd.get_dummies(data_test[['Quote','Weekday']], prefix = 'category')
print(data_test[['Quote','Weekday']].head())
print(df_test_dummies.head())

    Quote  Weekday
0  Medium  Weekend
1     Low  Weekend
2  Medium     Week
3    High     Week
4    High     Week
   category_High  category_Low  category_Medium  category_Week  \
0              0             0                1              0   
1              0             1                0              0   
2              0             0                1              1   
3              1             0                0              1   
4              1             0                0              1   

   category_Weekend  
0                 1  
1                 1  
2                 0  
3                 0  
4                 0  
    Quote Weekday
0  Medium    Week
1  Medium    Week
2     Low    Week
3     Low    Week
4     Low    Week
   category_High  category_Low  category_Medium  category_Week  \
0              0             0                1              1   
1              0             0                1              1   
2              0             1                0    

In [3]:
#Normalize numerical data
df_train_num = data_train[['Max Temp (C)', 'Min Temp (C)', 'Mean Temp (C)', 'Heat Deg Days (C)', 'Cool Deg Days (C)', 'Total Precip (mm)', 'Snow on Grnd (cm)']]
df_train_norm =(df_train_num-df_train_num.mean())/df_train_num.std()

df_test_num = data_test[['Max Temp (C)', 'Min Temp (C)', 'Mean Temp (C)', 'Heat Deg Days (C)', 'Cool Deg Days (C)', 'Total Precip (mm)', 'Snow on Grnd (cm)']]
df_test_norm =(df_test_num-df_test_num.mean())/df_test_num.std()

print(df_train_norm.head())
print(df_test_norm.head())

   Max Temp (C)  Min Temp (C)  Mean Temp (C)  Heat Deg Days (C)  \
0     -0.459736     -1.315876      -0.881876           0.899217   
1     -1.417739     -1.657258      -1.554594           1.638827   
2     -0.881907     -0.886961      -0.898906           0.917941   
3     -1.149823     -0.886961      -1.035153           1.067736   
4     -1.304078     -1.517204      -1.426862           1.498394   

   Cool Deg Days (C)  Total Precip (mm)  Snow on Grnd (cm)  
0          -0.461139          -0.396177          -0.172335  
1          -0.461139           1.257476          -0.318179  
2          -0.461139          -0.425707           0.265197  
3          -0.461139          -0.425707           0.265197  
4          -0.461139          -0.425707           0.265197  
   Max Temp (C)  Min Temp (C)  Mean Temp (C)  Heat Deg Days (C)  \
0     -2.304671     -2.330328      -2.346575           2.605619   
1     -1.939861     -2.297272      -2.138192           2.368666   
2     -1.651054     -1.578319 

In [5]:
#Rebuild data frames with encoded and normalized data
data_train_encoded = pd.concat([df_train_norm, df_train_dummies], axis=1)
data_test_encoded = pd.concat([df_test_norm, df_test_dummies], axis=1)

# View the head of the DataFrames
print(data_train_encoded.head())
print(data_test_encoded.head())

   Max Temp (C)  Min Temp (C)  Mean Temp (C)  Heat Deg Days (C)  \
0     -0.459736     -1.315876      -0.881876           0.899217   
1     -1.417739     -1.657258      -1.554594           1.638827   
2     -0.881907     -0.886961      -0.898906           0.917941   
3     -1.149823     -0.886961      -1.035153           1.067736   
4     -1.304078     -1.517204      -1.426862           1.498394   

   Cool Deg Days (C)  Total Precip (mm)  Snow on Grnd (cm)  category_High  \
0          -0.461139          -0.396177          -0.172335              0   
1          -0.461139           1.257476          -0.318179              0   
2          -0.461139          -0.425707           0.265197              0   
3          -0.461139          -0.425707           0.265197              1   
4          -0.461139          -0.425707           0.265197              1   

   category_Low  category_Medium  category_Week  category_Weekend  
0             0                1              0                 1 

In [0]:
# Creating a matrix X for training, as a subset of the dataframe  that includes only the attributes 'Max Temp (C)', 'Min Temp (C)', 'Mean Temp (C)', 'Heat Deg Days (C)', 'Cool Deg Days (C)', 'Total Precip (mm)', 'Snow on Grnd (cm)', 'category_Week', 'category_Weekend'
X_train = data_train_encoded[['Max Temp (C)', 'Min Temp (C)', 'Mean Temp (C)', 'Heat Deg Days (C)', 'Cool Deg Days (C)', 'Total Precip (mm)', 'Snow on Grnd (cm)', 'category_Week', 'category_Weekend']].values

# Creating a response variable y for training that is the quote for that day given the weather and day of the week (week or weekend): 'category_High', 'category_Low', 'category_Medium', 
y_train = data_train_encoded[['category_High', 'category_Low', 'category_Medium']].values

# We do the same for the test data
X_test = data_test_encoded[['Max Temp (C)', 'Min Temp (C)', 'Mean Temp (C)', 'Heat Deg Days (C)', 'Cool Deg Days (C)', 'Total Precip (mm)', 'Snow on Grnd (cm)', 'category_Week', 'category_Weekend']].values
y_test = data_test_encoded[['category_High', 'category_Low', 'category_Medium']].values

In [0]:
# We'll do the same thing on multiple classifying methods: train the method on the training data and then predict on the test data and assess performance
# No cross validation on the training set will be done given it's too long on Neural Networks

# For a quick assesment of prediction performance on the test set, we'll be using the accuracy score and the confusion matrix for further analysis
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix


In [10]:


# Method 1: Random Forest

# Import the random forest model from the Scikit-learn library and run the algorithm (training)
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train,y_train)

# We now apply our predictive model on the test data (X_test) and compute the accuracy score
y_test_pred = rf.predict(X_test)
as_rf = accuracy_score(y_test, y_test_pred)
print(as_rf)

# To run the confusion we must decode the y_test_pred to compare it to the original 'Quote' column of the 2018 data Frame
# https://stackoverflow.com/questions/38334296/reversing-one-hot-encoding-in-pandas
# pd.get_dummies(y_test_pred).idxmax(1)
# Can't follow this method since the model output is not a Pandas dataframe

# We must invert encoding on an array beacuse this is what we get as output from the algorithm.
# https://stackoverflow.com/questions/43665041/how-compute-confusion-matrix-for-multiclass-classification-in-scikit?rq=1
from numpy import argmax
inverted_y_test_pred = [ np.argmax(t) for t in y_test_pred ]
inverted_y_test = [ np.argmax(t) for t in y_test ]

# print(inverted_y_test_pred)
# print(inverted_y_test)

# We can recompute the accuracy score on the arrays for consistency.
as_inv_rf = accuracy_score(inverted_y_test, inverted_y_test_pred)
print(as_inv_rf)

# Create the confusion matrix from the invert encoded targets.
cm_rf = confusion_matrix(inverted_y_test, inverted_y_test_pred)
print(cm_rf)

0.2735294117647059
0.31176470588235294
[[14  8 12]
 [53 14 81]
 [59 21 78]]


In [11]:
# Method 2: Neural networks

# Import, built and train a keras NN classifier model and run it 

# Import
import keras
from keras import layers
from keras.models import Sequential
from keras.layers import Dense

# Single fully connected hidden layer with the same number of neurons as input attributes (9).
# The network uses good practice such as the rectifier activation function for the hidden layer. 

# Build
nn = keras.Sequential()
nn.add(layers.Dense(9, activation='relu', input_shape=(9,)))
nn.add(layers.Dense(9, activation ='relu'))
nn.add(layers.Dense(3, activation='relu'))

nn.compile(loss='categorical_crossentropy', optimizer='adam')

# Train
# Fit the model
nn.fit(X_train, y_train, batch_size=10, epochs=50)


Using TensorFlow backend.


Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Epoch 1/50
4564/4564 [==============================] - 5s 1ms/step - loss: 2.3381
Epoch 2/50
4564/4564 [==============================] - 2s 409us/step - loss: 1.0406
Epoch 3/50
4564/4564 [==============================] - 2s 420us/step - loss: 1.0144
Epoch 4/50
4564/4564 [==============================] - 2s 419us/step - loss: 0.9982
Epoch 5/50
4564/4564 [==============================] - 2s 419us/step - loss: 0.9947
Epoch 6/50
4564/4564 [==============================] - 2s 422us/step - loss: 0.9925
Epoch 7/50
4564/4564 [==============================] - 2s 428us/step - loss: 0.9907
Epoch 8/50
4564/4564 [==============================] - 2s 418us/step - loss: 0.9904
Epoch 9/50
4564/4564 [==============================] - 2s 419us/step - loss: 0.9894
Epoch 10/50
4564/4564 [==============================] - 2s 428us/step - loss: 0.9889
Epoch 11/50
4564/4564 [========

In [0]:
# We now apply our predictive model on the test data (X_test) 
y_test_pred = nn.predict(X_test)

#Accuracy score cannot be directly calculated given the output of the NN are not dummy variables, we must invert encode before



In [14]:
# Invert encoding the targets
inverted_y_test_pred = [ np.argmax(t) for t in y_test_pred ]
inverted_y_test = [ np.argmax(t) for t in y_test ]

#print(inverted_y_test_pred)
#print(inverted_y_test)

# We can now compute the accuracy score
as_inv_nn = accuracy_score(inverted_y_test, inverted_y_test_pred)
print(as_inv_nn)

# Create the confusion matrix from the invert encoded targets.
from sklearn.metrics import confusion_matrix
cm_nn = confusion_matrix(inverted_y_test, inverted_y_test_pred)
print(cm_nn)

0.46176470588235297
[[  0   0  34]
 [  0   0 148]
 [  0   1 157]]
